# Generated by Django 3.0 on 2020-06-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=20)),
                ('no_of_covid_patients', models.IntegerField()),
                ('no_of_beds', models.IntegerField()),
                ('no_of_ppe_kits', models.IntegerField()),
                ('no_of_masks', models.IntegerField()),
                ('no_of_icu_beds', models.IntegerField(default='0')),
                ('category', models.CharField(choices=[('COVID care centre', 'COVID care centre'), ('Dedicated COVID health centre', 'Dedicated COVID health centre'), ('Dedicated COVID hospital', 'Dedicated COVID hospital')], default='COVID care centre', max_length=50)),
                ('no_of_ventilators', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Corona_warrior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_quarantined', models.BooleanField()),
                ('quarantined_since', models.DateField(blank=True, null=True)),
                ('last_placed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('is_god', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('area', models.CharField(blank=True, choices=[('Dadar', 'Dadar'), ('South-Bombay', 'South-Bombay'), ('Bandra', 'Bandra'), ('Borivali', 'Borivali'), ('Chembur', 'Chembur'), ('Andheri', 'Andheri'), ('Powai', 'Powai'), ('Thane', 'Thane')], max_length=20, null=True)),
                ('hospital', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.Hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
