# Generated by Django 3.0 on 2020-06-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='area',
            field=models.CharField(blank=True, choices=[('Dadar', 'Dadar'), ('South-Bombay', 'South-Bombay'), ('Bandra', 'Bandra'), ('Borivali', 'Borivali'), ('Chembur', 'Chembur'), ('Andheri', 'Andheri'), ('Powai', 'Powai'), ('Thane', 'Thane')], max_length=20, null=True),
        ),
    ]
