# Generated by Django 3.0.6 on 2020-06-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_auto_20200615_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='corona_warrior',
            name='working_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
